### ISSUE TITLE
High Sierra Java Exception

### ISSUE THREAD

**Issue by eboye** [grakic/jfreesteel#10]
Pokretanje alikacije direktno ne uspeva na MacOS High Sierra
Pokretanjem iz terminala ./JavaAppLauncher dobijam ovaj exception

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
	at net.devbase.jfreesteel.viewer.EidViewer.createAndShowGUI(EidViewer.java:174)
	at net.devbase.jfreesteel.viewer.EidViewer.access$7(EidViewer.java:157)
	at net.devbase.jfreesteel.viewer.EidViewer$1.run(EidViewer.java:137)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

Jel ovo problem do aplikacije ili mu nešto fali na sistemu?

**Comment by grakic** [comment]
Izgleda da se problem javlja pri učitavanju ikonice prozora. Da li postoji bilo šta neobično u konfiguraciji tog računara? Koja verzija Jave je instalirana?

**Comment by eboye** [comment]
```
java -version
javac 9.0.4
```

Specifično može biti da je hackintosh u pitanju, ali to ne bi trebalo da menja stvari. Java je instalirana preko homebrew-a.

**Comment by vdjurdjevic** [comment]
Isti problem imam na linux-u: 

DISTRIB_ID=Zorin
DISTRIB_RELEASE=15
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Zorin OS 15.1"
NAME="Zorin OS"
VERSION="15.1"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 15.1"
VERSION_ID="15"
HOME_URL="https://www.zorinos.com"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

@eboye Jesi uspeo da resis problem?

**Comment by eboye** [comment]
@vdjurdjevic jesam, reinstalacijom OS-a od nule.

**Comment by vdjurdjevic** [comment]
Hm, to mi se bas ne radi.. Relativno je sveza istalacija. Probacu veceras
da debagujem pa da vidim sta je problem

**Comment by vdjurdjevic** [comment]
Problem je bio u verziji Jave. Zorin OS (Ubuntu bionic) koristi v11. Instalirao sam dodatno v8 i postavio je za default verziju, sad aplikacija radi. @grakic Mozda ne bi bilo lose update-ovati app da radi sa novijim verzijama jave. Ja bih rado odradio, ali ne radim sa Javom, nisam uspeo ni Maven da nateram da kompajlira projekat, ne moze neki dependency da download-uje zbog sertifikata.. Kontam da ce neko ko radi to na dnevnoj bazi mnogo brze resiti problem od mene.

**Comment by eboye** [comment]
@vdjurdjevic radi, probao sam da kompajliram i da prebacim novi jar u aplikaciju. Dodatno za one koji pokreću app na Mojave i Catalina MacOS verzijama, potrebno je da se isključi gatekeeper da bi mogla da se pokrene:

`sudo xattr -rd com.apple.quarantine /Applications/JFreesteel\ eID\ Viewer.app`
