### ISSUE TITLE
“JFreesteel eID Viewer” will damage your computer. You should move it to the Bin.

### ISSUE THREAD

**Issue by ratomirjovanovic** [grakic/jfreesteel#12]
<img width="422" alt="Screenshot 2020-04-21 at 12 37 56" src="https://user-images.githubusercontent.com/23360834/79856806-245f9680-83cd-11ea-9509-8c80558f1d4f.png">

**Comment by filmil** [comment]
Било би згодно када би програм просто био потписан. Шта је потребно за то?

**Comment by ratomirjovanovic** [comment]
Izvini, nisam razumeo komentar a ni pitanje. 
Prilikom instalacije macOS je izbacio gresku. 
Na macOS Catalina vise ne postoji opcija "open from untrusted developer".

**Comment by filmil** [comment]
Јасно - моје питање је било како постати trusted developer.

**Comment by ratomirjovanovic** [comment]
https://developer.apple.com/programs/enroll/

**Comment by ratomirjovanovic** [comment]
Da li postoji resenje za ovo?

**Comment by filmil** [comment]
Постоји. Треба да се неко региструје као старатељ програма Еплу, и да се направи потписан инсталатер за Мека. Пинг, @grakic! :)

Искрено, у данашње време не бих инсталирао ниједан непотписан пакет.
Шансе су скоро 100% да тако на свом рачунару покрећеш нешто што рудари биткоин на твоју струју.

**Comment by grakic** [comment]
Čekamo na Apple da odobri novi dev account...

![Screenshot from 2020-05-04 00-30-03](https://user-images.githubusercontent.com/712022/80927480-7f669580-8d9e-11ea-9630-6b59276e5dd7.png)

**Comment by dusandevic** [comment]
Uspeo sam da pokrenem aplikaciju na sledeći način: 

- Desni klik na JFreesteel eID Viewer pa Show Package Contents
- Otvoriti Java folder
- Dvoklik na eidviewer-1.1.jar

Naravno, sve to može i iz terminala:
- cd /Applications/JFreesteel\ eID\ Viewer.app/Contents/Java
- java -jar eidviewer-1.1.jar

**Comment by ratomirjovanovic** [comment]
Upravo probah i jedan i drugi nacin, ali bezuspesno. 
Kada idem klik na eidviewer-1.1.jar  (ili kada pozovem iz terminala) otvori mi se java i zatvori. 

Evo ga i output
` Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
	at net.devbase.jfreesteel.viewer.EidViewer.createAndShowGUI(EidViewer.java:174)
	at net.devbase.jfreesteel.viewer.EidViewer.access$7(EidViewer.java:157)
	at net.devbase.jfreesteel.viewer.EidViewer$1.run(EidViewer.java:137)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90))`

**Comment by milmih** [comment]
I ja imam isti problem. Je l' neko uspeo da pokrene aplikaciju kod sebe? Hvala!

**Comment by srlek** [comment]
![image](https://user-images.githubusercontent.com/77169750/104053061-eae4ea80-51ea-11eb-9827-1995d037d52e.png)
App info, stiklirati Overide Malware Protection - MacOS - BigSur, nakon toga app se pokrece ali izbacuje gresku da ne vidi Card Reader:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/77169750/104053251-36979400-51eb-11eb-8e71-62f485d3352e.png">
Na MacOS Catalina radi sasvim OK !

**Comment by srlek** [comment]
pokretanje aplokacije is terminala daje gresku:

[AWT-EventQueue-0] ERROR net.devbase.jfreesteel.EidCard - Reader error
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4456)
	at net.devbase.jfreesteel.viewer.EidViewer.pickTerminalGUI(EidViewer.java:243)
	at net.devbase.jfreesteel.viewer.EidViewer.createAndShowGUI(EidViewer.java:206)
	at net.devbase.jfreesteel.viewer.EidViewer.access$7(EidViewer.java:157)
	at net.devbase.jfreesteel.viewer.EidViewer$1.run(EidViewer.java:137)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by eboye** [comment]
Isto, upgrade-ovao na Big Sur i app je prestala sa radom. Ovo za malware sam štiklirao i pali je ali ne detektuje Smart Card Reader
![image](https://user-images.githubusercontent.com/624357/126082305-1c163596-c407-4dcf-ba10-0ed13b11bd91.png)

**Comment by Ptiki** [comment]
Izvadio sam novu ličnu kartu ovog meseca, pa reko' da probam ponovo...
Na macOS Catalina 10.15.7 situacija je sledeća:
- kada se uradi Override Malware Protection:
![Screenshot 2021-11-18 at 13 22 18](https://user-images.githubusercontent.com/69478278/142414591-512275c9-7023-4048-9bbb-a5628bda0dea.png)
dobije se ovo:
![Screenshot 2021-11-18 at 13 23 43](https://user-images.githubusercontent.com/69478278/142414781-e9136103-5f36-48ab-bb4a-56137df3cf58.png)
iako je lična karta u čitaču.

Ima li bilo kakve šanse da, ako već ne možemo da nateramo državu, barem podelimo troškove oko dev accounta (ili šta već treba) za ovo... samo da počne da radi?
 
Hvala @grakic @eboye i svima drugima puno!

**Comment by eboye** [comment]
@Ptiki ja sam prešao na linux gde radi OK, ne koristim više MacOS. Dodatno licenca je 100$, al godišnje, tako da mislim da bi tu bilo najbolje da neko ko ima Apple Dev nalog zapravo potpiše app.

Ja sam inače probao da kompajliram app za MacOS, međutim nisam uspeo zbog raznih problema sa verzijom jave i sl.

**Comment by joksa** [comment]
Nazalost izgleda da je napusten projekat
